-- no-transaction
--
-- Index for reading the log in commit order: transaction first, then position within it
-- (funkode-io/replay#193). Without it, `ORDER BY commit_txid, global_position` is a scan
-- plus a sort of the whole table; with it, it is a forward index scan a cursor can page.
--
-- Not partial on `compacted_snapshot` the way `idx_events_policy_feed` is: the reader
-- this index is for does not exist yet (funkode-io/replay#171), and the feed advances its
-- cursor across snapshot rows even though it delivers none of them (ADR-0013).
--
-- CONCURRENTLY, hence `-- no-transaction` above and one statement in this file: a plain
-- CREATE INDEX holds a lock that blocks appends for the length of the build, and
-- CONCURRENTLY cannot run inside a transaction block.
--
-- Outside a transaction the build and sqlx's record of it are two operations, so a retry
-- has two states to survive, and they pull in opposite directions:
--
--   * Built, and then the process died before the record was written. `IF NOT EXISTS`
--     makes the retry a no-op that records the migration, so this heals itself.
--   * The build failed or was cancelled, leaving an *invalid* index of this name,
--     maintained on every write and used by no query. `IF NOT EXISTS` skips it, so this
--     statement on its own would record the migration over a broken schema.
--
-- So `IF NOT EXISTS` stays and 0016 — an ordinary transactional migration — refuses to
-- apply while the index is invalid. Whatever this one adopts, the next one checks.
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_events_commit_txid_position
    ON events (commit_txid, global_position);
