-- Redundant now: 0015's unique index has the same column list and serves the policy
-- feed's `WHERE global_position > $cursor ORDER BY global_position` scan identically.
--
-- Dropped after the unique index exists, not before, so a live deployment never runs a
-- moment without an index on the column the feed reads.
--
-- `idx_events_policy_feed` (0009) is left in place: it is partial on
-- `compacted_snapshot = FALSE`, and since ADR-0013 the feed reads positions unfiltered,
-- so nothing matches its predicate any more. Removing it is a separate question from this
-- one, on its own evidence.
DROP INDEX IF EXISTS idx_events_global_position;
